# Generated by Django 5.2.17 on 2026-09-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('input_type', models.CharField(choices=[('text', 'Text Input'), ('url', 'URL Input')], default='text', max_length=10)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('result', models.CharField(max_length=50)),
                ('confidence', models.FloatField(default=0.0)),
                ('source_info', models.CharField(blank=True, max_length=255)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('model_predictions', models.JSONField(blank=True, default=dict)),
                ('explanation', models.JSONField(blank=True, default=list)),
                ('response_time_ms', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndexedNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('summary', models.TextField(blank=True, default='')),
                ('source', models.CharField(db_index=True, default='Seed Dataset', max_length=200)),
                ('label', models.CharField(choices=[('real', 'Real News'), ('fake', 'Fake News')], db_index=True, max_length=10)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('content_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Protected reference article that will not be purged by retention cleanup.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['label', 'created_at'], name='detection_i_label_534c18_idx'), models.Index(fields=['content_hash'], name='detection_i_content_31e1a0_idx')],
            },
        ),
    ]
