# Generated by Django 5.2.17 on 2026-09-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_setup_fts5'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionlog',
            name='bias_label',
            field=models.CharField(blank=True, default='', help_text="Detected bias type, e.g. 'Political Right', 'Emotional Alarmism'.", max_length=100),
        ),
        migrations.AddField(
            model_name='detectionlog',
            name='is_reviewed',
            field=models.BooleanField(default=False, help_text='Set to True once a human reviewer has validated this detection.'),
        ),
        migrations.AddField(
            model_name='detectionlog',
            name='needs_review',
            field=models.BooleanField(db_index=True, default=False, help_text='Auto-flagged when confidence is in the borderline 40–65% range.'),
        ),
        migrations.AddField(
            model_name='detectionlog',
            name='political_lean',
            field=models.CharField(blank=True, default='', help_text='Detected political lean: left, right, center, or neutral.', max_length=20),
        ),
        migrations.AddField(
            model_name='detectionlog',
            name='reviewer_verdict',
            field=models.CharField(blank=True, default='', help_text='Human reviewer override verdict.', max_length=50),
        ),
    ]
