# Generated by Django 5.2.4 on 2025-07-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
