# Generated by Django 5.2.4 on 2025-08-09 04:15

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image (JPG, PNG, GIF, WebP). Maximum size: 5MB.', null=True, upload_to='articles/', validators=[accounts.models.validate_image_extension, accounts.models.validate_image_size]),
        ),
    ]
